USE PROYECTO_VIVIENDA_CABA;

DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.CURATED_ZONE.CUZ_TBL_L2_FACT_COMPRA_MT2;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.CURATED_ZONE.CUZ_TBL_L2_FACT_DELITOS_2023_CABA;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.CURATED_ZONE.CUZ_TBL_L2_FACT_PRECIO_ALQUILER;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.CURATED_ZONE.CUZ_TBL_L3_FACT_PRECIOS_PROPIEDADES;

CREATE TABLE PROYECTO_VIVIENDA_CABA.CURATED_ZONE.CUZ_TBL_L2_FACT_COMPRA_MT2 (
	ID INTEGER PRIMARY KEY,
	ID_BARRIO INTEGER,
	PRECIO_USD INTEGER,
	FECHA DATE
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CURATED_ZONE.CUZ_TBL_L2_FACT_DELITOS_2023_CABA (
	ID_DELITO INTEGER PRIMARY KEY,
	TIPO VARCHAR(50),
	USO_ARMA VARCHAR(50),
	ID_BARRIO INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CURATED_ZONE.CUZ_TBL_L2_FACT_PRECIO_ALQUILER (
	ID INTEGER PRIMARY KEY,
	ID_BARRIO INTEGER,
	ID_TIPO_DEPARTAMENTO INTEGER,
	PRECIO INTEGER,
	FECHA DATE
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CURATED_ZONE.CUZ_TBL_L3_FACT_PRECIOS_PROPIEDADES (
	ID_PRECIOS_PROPIEDADES INTEGER PRIMARY KEY,
	ID_BARRIO INTEGER,
	ID_TIPO_DEPARTAMENTO INTEGER,
	PRECIO_ALQUILER_PESOS INTEGER,
	PRECIO_COMPRA_APROXIMADO_USD INTEGER,
	FECHA DATE
);