USE PROYECTO_VIVIENDA_CABA;

DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_BANCOS;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_BARRIOS;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_INDUSTRIAS;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_PUESTOS_TRABAJO;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_SENIORITY;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_TIPO_DEPARTAMENTO;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_COMPRA_MT2;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_DELITOS_2023_CABA;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_HISTORICO_PRECIOS_PROMEDIO_ALQUILERES_CABA;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_HISTORICO_VARIACION_SALARIOS_TRABAJADORES_REGISTRADOS_PRIVADOS;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_PRECIO_ALQUILER_DOS_AMBIENTES;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_PRECIO_ALQUILER_MONOAMBIENTE;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_PRECIO_ALQUILER_TRES_AMBIENTES;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_PRESTAMOS_HIPOTECARIOS;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_SUELDOS;
DROP TABLE IF EXISTS PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_VARIACION_INFLACION;


CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_BANCOS (
	ID_BANCO INTEGER PRIMARY KEY,
	NOMBRE VARCHAR(50)
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_BARRIOS (
	ID_BARRIO INTEGER PRIMARY KEY,
	BARRIO VARCHAR(50),
	COMUNA INTEGER,
	LATITUD FLOAT,
	LONGITUD FLOAT
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_INDUSTRIAS (
	ID_INDUSTRIA INTEGER PRIMARY KEY,
	NOMBRE_INDUSTRIA VARCHAR(50)
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_PUESTOS_TRABAJO (
	ID_PUESTO_TRABAJO INTEGER PRIMARY KEY,
	NOMBRE_PUESTO VARCHAR(50) NOT NULL,
	ID_INDUSTRIA INTEGER,
	ID_SENIORITY INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_SENIORITY (
	ID_SENIORITY INTEGER PRIMARY KEY,
	NOMBRE_SENIORITY VARCHAR(50),
	DESCRIPCION VARCHAR(70)
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_TIPO_DEPARTAMENTO (
	ID_TIPO_DEPARTAMENTO INTEGER PRIMARY KEY,
	TIPO_DEPARTAMENTO VARCHAR(50),
	MT2_PROMEDIO INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_COMPRA_MT2 (
	BARRIO VARCHAR(50),
	VALOR_MT2_USD INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_DELITOS_2023_CABA (
	ID_DELITO INTEGER PRIMARY KEY,
	TIPO VARCHAR(50),
	USO_ARMA VARCHAR(50),
	ID_BARRIO INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_HISTORICO_PRECIOS_PROMEDIO_ALQUILERES_CABA (
	MONO_AMBIENTE FLOAT,
	DOS_AMBIENTES FLOAT,
	TRES_AMBIENTES FLOAT,
	ANIO INTEGER,
	VARIACION_ANUAL_1_AMBIENTE FLOAT,
	VARIACION_ANUAL_2_AMBIENTES FLOAT,
	VARIACION_ANUAL_3_AMBIENTES FLOAT
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_HISTORICO_VARIACION_SALARIOS_TRABAJADORES_REGISTRADOS_PRIVADOS (
	ID INTEGER PRIMARY KEY,
	ANIO INTEGER,
	VARIACION_ANIO_ANTERIOR FLOAT,
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_PRECIO_ALQUILER_DOS_AMBIENTES (
	ID_BARRIO INTEGER,
	PRECIO FLOAT,
    --FOREIGN KEY (ID_BARRIO) REFERENCES PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_BARRIOS(ID_BARRIO)
);


CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_PRECIO_ALQUILER_MONOAMBIENTE (
	ID_BARRIO INTEGER,
	PRECIO FLOAT,
	--FOREIGN KEY (ID_BARRIO) REFERENCES PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_BARRIOS(ID_BARRIO)
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_PRECIO_ALQUILER_TRES_AMBIENTES (
	ID_BARRIO INTEGER,
	PRECIO FLOAT,
	--FOREIGN KEY (ID_BARRIO) REFERENCES PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_BARRIOS(ID_BARRIO)
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_PRESTAMOS_HIPOTECARIOS (
	ID_PRESTAMO INTEGER PRIMARY KEY,
	ID_BANCO INTEGER,
	SUELDO_INGRESADO INTEGER,
	PRECIO_PROPIEDAD_USD INTEGER,
	PRECIO_PROPIEDAD_PESOS INTEGER,
	MONTO_OTORGADO INTEGER,
	PRIMERA_CUOTA_PESOS INTEGER,
	ANIOS_DEVOLUCION INTEGER,
	ID_BARRIO INTEGER,
	ID_TIPO_DEPARTAMENTO INTEGER,
	--FOREIGN KEY (ID_BARRIO) REFERENCES PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_DIM_BARRIOS(ID_BARRIO)
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_SUELDOS (
	ID_SUELDO INTEGER PRIMARY KEY,
	SUELDO_NETO INTEGER,
	ID_PUESTO_TRABAJO INTEGER,
	FECHA DATE
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.LANDING_ZONE.L1_FACT_VARIACION_INFLACION (
	ID_INFLACION INTEGER PRIMARY KEY,
	ANIO INTEGER,
	VARIACION FLOAT
);


