


CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L1_FACT_EXCHANGE_RATE (
	FECHA DATE,
	PRECIO INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L1_FACT_PRECIO_UVA (
	FECHA DATE,
	PRECIO INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L1_FACT_SUELDOS_MINIMOS (
	ID_SUELDO_MINIMO INTEGER PRIMARY KEY,
	FECHA DATE,
	SUELDO_MINIMO INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_DIM_BANCOS (
	ID_BANCO INTEGER PRIMARY KEY,
	NOMBRE VARCHAR(60)
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_DIM_BARRIOS (
	ID_BARRIO INTEGER PRIMARY KEY,
	BARRIO VARCHAR(60),
	COMUNA INTEGER,
	LATITUD FLOAT,
	LONGITUD FLOAT
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_DIM_INDUSTRIAS (
	ID_INDUSTRIA INTEGER PRIMARY KEY,
	NOMBRE_INDUSTRIA VARCHAR(60)
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_DIM_PUESTOS_TRABAJO (
	ID_PUESTO_TRABAJO INTEGER PRIMARY KEY,
	NOMBRE_PUESTO VARCHAR(50) NOT NULL,
	ID_INDUSTRIA INTEGER,
	ID_SENIORITY INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_DIM_SENIORITY (
	ID_SENIORITY INTEGER,
	NOMBRE_SENIORITY VARCHAR(50),
	DESCRIPCION VARCHAR(60)
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_DIM_TIPO_DEPARTAMENTO (
	ID_TIPO_DEPARTAMENTO INTEGER PRIMARY KEY,
	TIPO_DEPARTAMENTO VARCHAR(50),
	MT2_PROMEDIO INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_FACT_HISTORICO_PRECIOS_PROMEDIOS_ALQUILER_CABA (
	MONO_AMBIENTE INTEGER,
	DOS_AMBIENTES INTEGER,
	TRES_AMBIENTES INTEGER,
	ANIO INTEGER,
	VARIACION_ANUAL_MONO_AMBIENTE FLOAT,
	VARIACION_ANUAL_DOS_AMBIENTES FLOAT,
	VARIACION_ANUAL_TRES_AMBIENTES FLOAT
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_FACT_HISTORICO_VARIACION_SALARIOS_TRABAJADORES_REGISTRADOS_PRIVADOS (
	ID INTEGER PRIMARY KEY,
	ANIO INTEGER,
	VARIACION_ANIO_ANTERIOR FLOAT
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_FACT_PRESTAMOS_HIPOTECARIOS (
	ID_PRESTAMO INTEGER PRIMARY KEY,
	ID_BANCO INTEGER,
	SUELDO_INGRESADO INTEGER,
	PRECIO_PROPIEDAD_USD INTEGER,
	PRECIO_PROPIEDAD_PESOS INTEGER,
	MONTO_OTORGADO FLOAT,
	PRIMERA_CUOTA_PESOS FLOAT,
	ANIOS_DEVOLUCION INTEGER,
	ID_BARRIO INTEGER,
	ID_TIPO_DEPARTAMENTO INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_FACT_SUELDOS (
	ID_SUELDO INTEGER PRIMARY KEY,
	SUELDO_NETO INTEGER,
	ID_PUESTO_TRABAJO INTEGER,
	FECHA DATE
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L2_FACT_VARIACION_INFLACION (
	ID INTEGER PRIMARY KEY,
	ANIO INTEGER,
	VARIACION_INFLACION_ANIO_ANTERIOR FLOAT
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L3_FACT_DELITOS_2023_CABA (
	ID_DELITO INTEGER PRIMARY KEY,
	TIPO VARCHAR(50),
	USO_ARMA VARCHAR(20),
	ID_BARRIO INTEGER
);

CREATE TABLE PROYECTO_VIVIENDA_CABA.CONSUMPTION_ZONE.COZ_TBL_L4_FACT_PRECIOS_PROPIEDADES (
	ID_PRECIOS_PROPIEDADES INTEGER PRIMARY KEY,
	ID_BARRIO INTEGER,
	ID_TIPO_DEPARTAMENTO INTEGER,
	PRECIO_ALQUILER_PESOS INTEGER,
	PRECIO_COMPRA_APROXIMADO_USD INTEGER,
	FECHA DATE
);